import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  wrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    maxWidth: 500,
  },
  container: {
    width: "100%",
    maxWidth: 500,
    borderRadius: 2,
    background: "#fff",
    outline: "none",
    position: "relative",
    border: "none",
  },
  bordered: {
    border: [1, "solid", "#ccc"],
  },
  select: {
    width: "100%",
    height: "100%",
    borderRadius: 2,
    background: "transparent",
    paddingInline: 12,
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    cursor: "pointer",
  },
  arrow: {
    position: "absolute",
    right: 12,
    top: 10,
    height: "100%",
  },
  clear: {
    position: "absolute",
    right: 32,
    top: 10,
    height: "100%",
  },
  item: {
    width: "100%",
    padding: [8, 16],
    transition: "background 300ms ease",
    cursor: "pointer",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    "&:hover": {
      background: "#f2f2f2",
    },
  },
  noContent: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: 200,
    width: "100%",
  },
  selected: {
    background: "#f2f2f2",
  },
  disabled: {
    backgroundColor: "#f9f9f9",
    color: "#ccc",
    cursor: "not-allowed !important",
  },
  search: {
    width: "calc(100% - 32px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 38,
    margin: [16, "auto"],
    border: [1, "solid", "#ccc"],
    borderRadius: 2,
    position: "relative",
  },
  input: {
    outline: "none",
    border: "none",
    background: "transparent",
    width: "100%",
    height: 38,
    paddingInline: 8,
  },
  searchIcon: {
    right: 12,
    top: 9,
    position: "absolute",
  },
});
