export const persistKey = {
  ACCOUNTS: "ACCOUNTS",
  AUTHENTICATION: "AUTHENTICATION",
  USER_DETAILS: "USER_DETAILS",
  THEME: "THEME",
  LOCALIZE: "LOCALIZE",
  BANK: "BANK",
  TOOLBAR: "TOOLBAR",
};
