import { createUseStyles } from "react-jss";

export default createUseStyles({
  imagePreviewTitle: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    minHeight: 50,
    height: "auto",
    background: "rgba(50,50,50,.6)",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
  },
  tools: {
    position: "absolute",
    zIndex: 3,
    right: 0,
    top: 0,
    height: "100%",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    direction: "rtl",
    padding: [0, 16],
    fontSize: 24,
  },
  counter: {
    position: "absolute",
    zIndex: 3,
    left: 0,
    top: 0,
    height: "100%",
    width: "auto",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    padding: [0, 16],
    fontSize: 18,
  },
  tool: {
    minWidth: 40,
    minHeight: 40,
    fontSize: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    borderRadius: 4,
    marginInline: 4,
    "&:hover": {
      backgroundColor: "rgba(100,100,100,.7)",
    },
  },
  disabledZoom: {
    pointerEvents: "none",
    cursor: "default",
    opacity: 0.6,
  },
});
